package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"github.com/swiftwave-org/swiftwave/swiftwave_service/logger"
)

// FetchSystemLogRecords is the resolver for the fetchSystemLogRecords field.
func (r *queryResolver) FetchSystemLogRecords(ctx context.Context) ([]*string, error) {
	return logger.FetchSystemLogRecords()
}
