package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"os"
	"os/exec"
	"time"

	"github.com/fatih/color"
)

// RestartSystem is the resolver for the restartSystem field.
func (r *mutationResolver) RestartSystem(ctx context.Context) (bool, error) {
	go func() {
		<-time.After(2 * time.Second)
		color.Green("Restarting swiftwave service")
		color.Yellow("Swiftwave service will be restarted in 2 seconds")
		color.Yellow("If you are running without enabling service, run `swiftwave start` to start the service")
		out, err := exec.Command("systemctl", "restart", "swiftwave.service").CombinedOutput()
		if err != nil {
			color.Red("Failed to restart swiftwave.service: %v", err)
			if len(out) > 0 {
				color.Red("systemctl output: %s", string(out))
			}
			color.Yellow("System may be in a broken state — run `systemctl status swiftwave.service` and restart manually if needed")
			// Do NOT os.Exit — leaving the current process alive lets the operator
			// recover instead of dropping the API entirely on a failed restart.
			return
		}
		os.Exit(0)
	}()
	return true, nil
}
