package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"os"
	"os/exec"
	"time"

	"github.com/fatih/color"
)

// RestartSystem is the resolver for the restartSystem field.
func (r *mutationResolver) RestartSystem(ctx context.Context) (bool, error) {
	go func() {
		<-time.After(2 * time.Second)
		color.Green("Restarting swiftwave service")
		color.Yellow("Swiftwave service will be restarted in 2 seconds")
		color.Yellow("If you are running without enabling service, run `swiftwave start` to start the service")
		_ = exec.Command("systemctl", "restart", "swiftwave.service").Run()
		os.Exit(1)
	}()
	return true, nil
}
